### ISSUE TITLE
EventsController.php SQL Error

### ISSUE THREAD

**Issue by SomeAtaraxy** [ZoneMinder/zoneminder#2166]
I followed zmNinja's instructions to update the `EventsController.php` to the latest unreleased version in their FAQ wiki and it started causing the SQL error at the bottom of this message. The issue is that some code on May 7-8, 2018 and it incorrectly queries the db. If I comment out:
`$event['Event']['fileExists'] = $this->Event->fileExists($event['Event']);`
then the next line starts complaining:
`$event['Event']['fileSize'] = $this->Event->fileSize($event['Event']);`

Please note that *all* of the other ZM files are from the 1.30.4 release. I only updated the one file (`EventsController.php`).

### SQL Error:
```
2018-07-21 14:10:29 Error: [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right synta
x to use near 'fileExists' at line 1
Request URL: /api/events/93.json
Stack Trace:
#0 /usr/local/www/zoneminder/api/lib/Cake/Model/Datasource/DboSource.php(461): PDOStatement->execute(Array)
#1 /usr/local/www/zoneminder/api/lib/Cake/Model/Datasource/DboSource.php(427): DboSource->_execute('fileExists', Array)
#2 /usr/local/www/zoneminder/api/lib/Cake/Model/Datasource/DboSource.php(664): DboSource->execute('fileExists', Array, Array)
#3 /usr/local/www/zoneminder/api/lib/Cake/Model/Datasource/DboSource.php(607): DboSource->fetchAll('fileExists', Array, Array)
#4 /usr/local/www/zoneminder/api/lib/Cake/Model/Model.php(827): DboSource->query('fileExists', Array, Object(Event))
#5 /usr/local/www/zoneminder/api/app/Controller/EventsController.php(128): Model->__call('fileExists', Array)
#6 /usr/local/www/zoneminder/api/app/Controller/EventsController.php(128): Event->fileExists(Array)
#7 [internal function]: EventsController->view('93')
#8 /usr/local/www/zoneminder/api/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#9 /usr/local/www/zoneminder/api/app/Plugin/Crud/Lib/CrudControllerTrait.php(31): Controller->invokeAction(Object(CakeRequest))
#10 /usr/local/www/zoneminder/api/lib/Cake/Routing/Dispatcher.php(193): AppController->invokeAction(Object(CakeRequest))
#11 /usr/local/www/zoneminder/api/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#12 /usr/local/www/zoneminder/api/app/webroot/index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}
```

**Comment by knight-of-ni** [comment]
Closing, since this is double post. 

You are following instructions from a third party site. Thus, the conversation belongs at that site, which you have already done: https://github.com/pliablepixels/zmNinja/issues/672
