### ISSUE TITLE
Montage Review: No video to playback

### ISSUE THREAD

**Issue by DanwithArduino** [ZoneMinder/zoneminder#3274]
**Describe Your Environment**
- Version of ZoneMinder [1.37]
- How you installed ZoneMinder [PPA - master]
- Full name and version of OS: Ubuntu 20.04
- Firefox 88.0.1 and Chrome 91.0.4472.77 (Official Build) (64-bit)

**Describe the bug**
Opening the Montage Review page yields no video to review. The camera box is empty and displays "evaluating fps" 

**To Reproduce**
1. Go to 'montage review'

**Debug Logs**
```
Opening the console in chrome yields: 

`/zm/?view=montagereview:1 GET http://192.168.1.118/zm/?view=montagereview 500 (Internal Server Error)`

`DevTools failed to load source map: Could not load content for http://192.168.1.118/zm/cache/bootstrap.bundle.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

`?view=montagereview:255 Uncaught SyntaxError: Unexpected token '<'`

The apache error.log

[Wed Jun 02 15:43:40.496828 2021] [mpm_prefork:notice] [pid 19246] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Wed Jun 02 15:43:40.496896 2021] [core:notice] [pid 19246] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jun 02 15:43:48.275410 2021] [mpm_prefork:notice] [pid 19246] AH00169: caught SIGTERM, shutting down
[Wed Jun 02 15:43:48.339212 2021] [mpm_prefork:notice] [pid 19595] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Wed Jun 02 15:43:48.339250 2021] [core:notice] [pid 19595] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jun 02 15:49:40.321054 2021] [mpm_prefork:notice] [pid 19595] AH00169: caught SIGTERM, shutting down
[Wed Jun 02 15:49:40.381632 2021] [mpm_prefork:notice] [pid 29131] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Wed Jun 02 15:49:40.381669 2021] [core:notice] [pid 29131] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jun 02 16:03:05.514647 2021] [cgi:warn] [pid 29133] [client 192.168.1.140:4992] AH01220: Timeout waiting for output from CGI script /usr/lib/zoneminder/cgi-bin/nph-zms, referer: http://192.168.1.118/zm/index.php?view=watch&mid=1
[Wed Jun 02 16:41:48.983888 2021] [cgi:warn] [pid 29133] [client 192.168.1.140:5760] AH01220: Timeout waiting for output from CGI script /usr/lib/zoneminder/cgi-bin/nph-zms, referer: http://192.168.1.118/zm/index.php?view=watch&mid=1
[Wed Jun 02 16:42:31.062997 2021] [php7:error] [pid 29474] [client 192.168.1.140:6125] PHP Fatal error:  Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone () in /usr/share/zoneminder/www/skins/classic/views/js/montagereview.js.php:3\nStack trace:\n#0 /usr/share/zoneminder/www/skins/classic/views/js/montagereview.js.php(3): DateTimeZone->__construct()\n#1 /usr/share/zoneminder/www/skins/classic/includes/functions.php(923): require_once('/usr/share/zone...')\n#2 /usr/share/zoneminder/www/skins/classic/views/montagereview.php(330): xhtmlFooter()\n#3 /usr/share/zoneminder/www/index.php(297): require_once('/usr/share/zone...')\n#4 {main}\n  thrown in /usr/share/zoneminder/www/skins/classic/views/js/montagereview.js.php on line 3, referer: http://192.168.1.118/zm/index.php?view=watch&mid=1
[Wed Jun 02 16:43:11.927845 2021] [php7:error] [pid 29851] [client 192.168.1.140:6240] PHP Fatal error:  Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone () in /usr/share/zoneminder/www/skins/classic/views/js/montagereview.js.php:3\nStack trace:\n#0 /usr/share/zoneminder/www/skins/classic/views/js/montagereview.js.php(3): DateTimeZone->__construct()\n#1 /usr/share/zoneminder/www/skins/classic/includes/functions.php(923): require_once('/usr/share/zone...')\n#2 /usr/share/zoneminder/www/skins/classic/views/montagereview.php(330): xhtmlFooter()\n#3 /usr/share/zoneminder/www/index.php(297): require_once('/usr/share/zone...')\n#4 {main}\n  thrown in /usr/share/zoneminder/www/skins/classic/views/js/montagereview.js.php on line 3, referer: http://192.168.1.118/zm/index.php?view=console
[Wed Jun 02 16:47:42.335788 2021] [php7:error] [pid 29851] [client 192.168.1.140:6582] PHP Fatal error:  Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone () in /usr/share/zoneminder/www/skins/classic/views/js/montagereview.js.php:3\nStack trace:\n#0 /usr/share/zoneminder/www/skins/classic/views/js/montagereview.js.php(3): DateTimeZone->__construct()\n#1 /usr/share/zoneminder/www/skins/classic/includes/functions.php(923): require_once('/usr/share/zone...')\n#2 /usr/share/zoneminder/www/skins/classic/views/montagereview.php(330): xhtmlFooter()\n#3 /usr/share/zoneminder/www/index.php(297): require_once('/usr/share/zone...')\n#4 {main}\n  thrown in /usr/share/zoneminder/www/skins/classic/views/js/montagereview.js.php on line 3, referer: http://192.168.1.118/zm/index.php?view=event&eid=5&filter[Query][terms][0][attr]=MonitorId&filter[Query][terms][0][op]=%3d&filter[Query][terms][0][val]=1&page=1
[Wed Jun 02 16:48:37.549280 2021] [php7:error] [pid 29474] [client 192.168.1.140:6638] PHP Fatal error:  Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone () in /usr/share/zoneminder/www/skins/classic/views/js/montagereview.js.php:3\nStack trace:\n#0 /usr/share/zoneminder/www/skins/classic/views/js/montagereview.js.php(3): DateTimeZone->__construct()\n#1 /usr/share/zoneminder/www/skins/classic/includes/functions.php(923): require_once('/usr/share/zone...')\n#2 /usr/share/zoneminder/www/skins/classic/views/montagereview.php(330): xhtmlFooter()\n#3 /usr/share/zoneminder/www/index.php(297): require_once('/usr/share/zone...')\n#4 {main}\n  thrown in /usr/share/zoneminder/www/skins/classic/views/js/montagereview.js.php on line 3, referer: http://192.168.1.118/zm/index.php?view=montage
[Wed Jun 02 16:59:30.274735 2021] [php7:error] [pid 29132] [client 192.168.1.140:7297] PHP Fatal error:  Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone () in /usr/share/zoneminder/www/skins/classic/views/js/montagereview.js.php:3\nStack trace:\n#0 /usr/share/zoneminder/www/skins/classic/views/js/montagereview.js.php(3): DateTimeZone->__construct()\n#1 /usr/share/zoneminder/www/skins/classic/includes/functions.php(923): require_once('/usr/share/zone...')\n#2 /usr/share/zoneminder/www/skins/classic/views/montagereview.php(330): xhtmlFooter()\n#3 /usr/share/zoneminder/www/index.php(297): require_once('/usr/share/zone...')\n#4 {main}\n  thrown in /usr/share/zoneminder/www/skins/classic/views/js/montagereview.js.php on line 3, referer: http://192.168.1.118/zm/index.php?view=montagereview
[Wed Jun 02 17:00:51.177835 2021] [php7:error] [pid 29979] [client 192.168.1.140:7562] PHP Fatal error:  Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone () in /usr/share/zoneminder/www/skins/classic/views/js/montagereview.js.php:3\nStack trace:\n#0 /usr/share/zoneminder/www/skins/classic/views/js/montagereview.js.php(3): DateTimeZone->__construct()\n#1 /usr/share/zoneminder/www/skins/classic/includes/functions.php(923): require_once('/usr/share/zone...')\n#2 /usr/share/zoneminder/www/skins/classic/views/montagereview.php(330): xhtmlFooter()\n#3 /usr/share/zoneminder/www/index.php(297): require_once('/usr/share/zone...')\n#4 {main}\n  thrown in /usr/share/zoneminder/www/skins/classic/views/js/montagereview.js.php on line 3, referer: http://192.168.1.118/zm/index.php?view=cycle
[Wed Jun 02 17:02:18.943541 2021] [php7:error] [pid 30006] [client 192.168.1.140:15895] PHP Fatal error:  Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone () in /usr/share/zoneminder/www/skins/classic/views/js/montagereview.js.php:3\nStack trace:\n#0 /usr/share/zoneminder/www/skins/classic/views/js/montagereview.js.php(3): DateTimeZone->__construct()\n#1 /usr/share/zoneminder/www/skins/classic/includes/functions.php(923): require_once('/usr/share/zone...')\n#2 /usr/share/zoneminder/www/skins/classic/views/montagereview.php(330): xhtmlFooter()\n#3 /usr/share/zoneminder/www/index.php(297): require_once('/usr/share/zone...')\n#4 {main}\n  thrown in /usr/share/zoneminder/www/skins/classic/views/js/montagereview.js.php on line 3, referer: http://192.168.1.118/zm/
[Wed Jun 02 17:04:43.010686 2021] [php7:error] [pid 29135] [client 192.168.1.140:26792] PHP Fatal error:  Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone () in /usr/share/zoneminder/www/skins/classic/views/js/montagereview.js.php:3\nStack trace:\n#0 /usr/share/zoneminder/www/skins/classic/views/js/montagereview.js.php(3): DateTimeZone->__construct()\n#1 /usr/share/zoneminder/www/skins/classic/includes/functions.php(923): require_once('/usr/share/zone...')\n#2 /usr/share/zoneminder/www/skins/classic/views/montagereview.php(330): xhtmlFooter()\n#3 /usr/share/zoneminder/www/index.php(297): require_once('/usr/share/zone...')\n#4 {main}\n  thrown in /usr/share/zoneminder/www/skins/classic/views/js/montagereview.js.php on line 3, referer: http://192.168.1.118/zm/?view=report_event_audit
[Wed Jun 02 17:21:18.938266 2021] [php7:error] [pid 29851] [client 192.168.1.140:29240] PHP Fatal error:  Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone () in /usr/share/zoneminder/www/skins/classic/views/js/montagereview.js.php:3\nStack trace:\n#0 /usr/share/zoneminder/www/skins/classic/views/js/montagereview.js.php(3): DateTimeZone->__construct()\n#1 /usr/share/zoneminder/www/skins/classic/includes/functions.php(923): require_once('/usr/share/zone...')\n#2 /usr/share/zoneminder/www/skins/classic/views/montagereview.php(330): xhtmlFooter()\n#3 /usr/share/zoneminder/www/index.php(297): require_once('/usr/share/zone...')\n#4 {main}\n  thrown in /usr/share/zoneminder/www/skins/classic/views/js/montagereview.js.php on line 3, referer: http://192.168.1.118/zm/?view=report_event_audit
[Wed Jun 02 17:29:09.767395 2021] [php7:error] [pid 29344] [client 192.168.1.140:14183] PHP Fatal error:  Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone () in /usr/share/zoneminder/www/skins/classic/views/js/montagereview.js.php:3\nStack trace:\n#0 /usr/share/zoneminder/www/skins/classic/views/js/montagereview.js.php(3): DateTimeZone->__construct()\n#1 /usr/share/zoneminder/www/skins/classic/includes/functions.php(923): require_once('/usr/share/zone...')\n#2 /usr/share/zoneminder/www/skins/classic/views/montagereview.php(330): xhtmlFooter()\n#3 /usr/share/zoneminder/www/index.php(297): require_once('/usr/share/zone...')\n#4 {main}\n  thrown in /usr/share/zoneminder/www/skins/classic/views/js/montagereview.js.php on line 3, referer: http://192.168.1.118/zm/?view=report_event_audit

```

**console log**

**Expected behavior**
this is different than v1.34 where I can see video as soon as the page is loaded. 

![image](https://user-images.githubusercontent.com/10458867/120525739-76336800-c3a6-11eb-8085-7d1fb5d56034.png)

**Comment by DanwithArduino** [comment]
This should be closed... The timezone was never set in zoneminder. Hopefully this issue helps someone else.

**Comment by connortechnology** [comment]
Good for you for figuring it out.  However not having timezone set SHOULDN'T break montagereview.  So we will fix it and then close this.
