### ISSUE TITLE
zmu/zms processes periodically hangs

### ISSUE THREAD

**Issue by legioner0** [ZoneMinder/zoneminder#3626]
Environment:
- Version of ZoneMinder: 1.36.12+dfsg1-1 + `zmeventnotification` v6.1.28 from sources
- How you installed ZoneMinder: apt-get install from default system repository + `apache2`
- Full name and version of OS: Ubuntu 22.04.1 LTS

zmu or zms processes periodically hangs - they all have state `SLl` in `ps auxf` output. 
Debug log with maximum debug level for hanged zmu process have no difference from correctly finished zmu process and looks like:
```
./zmu.log:11/07/22 00:46:18.656924 zmu[2762238].DB1-zm_logger.cpp/224 [LogOpts: level=DB9 effective=DB9, screen=OFF, database=INF, logfile=DB9->/var/log/zm/zmu.log, syslog=INF]
./zmu.log:11/07/22 00:46:18.657139 zmu[2762238].DB1-zm_user.cpp/150 [Inside zmLoadTokenUser, formed key=yohbuhohyiePh6ae]
./zmu.log:11/07/22 00:46:18.657278 zmu[2762238].DB1-zm_crypt.cpp/69 [Got admin as user claim from token]
./zmu.log:11/07/22 00:46:18.657337 zmu[2762238].DB1-zm_crypt.cpp/78 [Got IAT token=1667752339]
./zmu.log:11/07/22 00:46:18.657389 zmu[2762238].DB1-zm_user.cpp/155 [retrieved user 'admin' from token]
./zmu.log:11/07/22 00:46:18.657690 zmu[2762238].DB1-zm_user.cpp/186 [Authenticated user 'admin' via token with last revoke time: 0]
./zmu.log:11/07/22 00:46:18.658032 zmu[2762238].DB5-zm_db.cpp/165 [Success]
./zmu.log:11/07/22 00:46:18.658101 zmu[2762238].DB4-zm_image.cpp/403 [Blend: Using fast blend function]
./zmu.log:11/07/22 00:46:18.658154 zmu[2762238].DB4-zm_image.cpp/487 [Delta: Using standard delta functions]
./zmu.log:11/07/22 00:46:18.658206 zmu[2762238].DB4-zm_image.cpp/553 [Deinterlace: Using standard functions]
./zmu.log:11/07/22 00:46:18.658255 zmu[2762238].DB4-zm_image.cpp/566 [Image buffer copy: Using standard memcpy]
./zmu.log:11/07/22 00:46:18.658487 zmu[2762238].DB2-zm_storage.cpp/62 [Loading Storage for 1 using SELECT `Id`, `Name`, `Path`, `Type`, `Scheme` FROM `Storage` WHERE `Id`=1]
./zmu.log:11/07/22 00:46:18.658657 zmu[2762238].DB5-zm_db.cpp/165 [Success]
./zmu.log:11/07/22 00:46:18.658714 zmu[2762238].DB1-zm_storage.cpp/80 [Loaded Storage area 1 'Default']
./zmu.log:11/07/22 00:46:18.658766 zmu[2762238].DB1-zm_monitor.cpp/493 [Have camera type File]
./zmu.log:11/07/22 00:46:18.658815 zmu[2762238].DB1-zm_monitor.cpp/2336 [Reloading linked monitors for monitor Camera Entry, '(null)']
./zmu.log:11/07/22 00:46:18.658870 zmu[2762238].DB3-zm_monitor.cpp/570 [Decoding enabled: 1 function 3 Modect savejpegs 3 videowriter 0]
./zmu.log:11/07/22 00:46:18.658975 zmu[2762238].DB1-zm_packetqueue.cpp/660 [Setting pre_event_video_packet_count to 125]
./zmu.log:11/07/22 00:46:18.667093 zmu[2762238].DB1-zm_packetqueue.cpp/654 [Setting max_video_packet_count to 150]
./zmu.log:11/07/22 00:46:18.667258 zmu[2762238].DB1-zm_monitor.cpp/658 [mem.size(8) SharedData=760 TriggerData=560 VideoStoreData=4128 timestamps=48 images=3x2764800 = 8294400 total=8299960]
./zmu.log:11/07/22 00:46:18.667332 zmu[2762238].DB1-zm_monitor.cpp/694 [Loaded monitor 1(Camera Entry), 0 zones]
./zmu.log:11/07/22 00:46:18.667396 zmu[2762238].DB3-zm_monitor.cpp/917 [Connecting to monitor.  Purpose is 0]
./zmu.log:11/07/22 00:46:18.667462 zmu[2762238].DB3-zm_monitor.cpp/930 [Success opening mmap file at (/dev/shm/zm.mmap.1)]
./zmu.log:11/07/22 00:46:18.667532 zmu[2762238].DB3-zm_monitor.cpp/963 [MMap file size is 8299960]
./zmu.log:11/07/22 00:46:18.667589 zmu[2762238].DB1-zm_monitor.cpp/968 [Unable to map file /dev/shm/zm.mmap.1 (8299960 bytes) to locked memory, trying unlocked]
./zmu.log:11/07/22 00:46:18.667652 zmu[2762238].DB1-zm_monitor.cpp/971 [Mapped file /dev/shm/zm.mmap.1 (8299960 bytes) to unlocked memory]
./zmu.log:11/07/22 00:46:18.667707 zmu[2762238].DB3-zm_monitor.cpp/1004 [Aligning shared memory images to the next 64 byte boundary]
./zmu.log:11/07/22 00:46:18.667760 zmu[2762238].DB2-zm_camera.cpp/68 [New camera id: 1 width: 1280 line size: 3840 height: 720 colours: 3 subpixelorder: 6 capture: 0]
./zmu.log:11/07/22 00:46:18.667847 zmu[2762238].DB3-zm_monitor.cpp/1014 [Allocated 3 3 image buffers]
./zmu.log:11/07/22 00:46:18.667916 zmu[2762238].DB3-zm_monitor.cpp/1067 [Success connecting]
./zmu.log:11/07/22 00:46:18.668010 zmu[2762238].DB4-zm_packetqueue.cpp/69 [Done in destructor]
```

back trace from gdb for that hanged process:
```
__futex_abstimed_wait_common64 (private=128, cancel=true, abstime=0x0, op=265, expected=2762239, futex_word=0x7f50168c2910) at ./nptl/futex-internal.c:57
57      ./nptl/futex-internal.c: No such file or directory.
(gdb) bt
#0  __futex_abstimed_wait_common64 (private=128, cancel=true, abstime=0x0, op=265, expected=2762239, futex_word=0x7f50168c2910) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=128, abstime=0x0, clockid=0, expected=2762239, futex_word=0x7f50168c2910) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x7f50168c2910, expected=2762239, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=128) at ./nptl/futex-internal.c:139
#3  0x00007f501e7f16a4 in __pthread_clockjoin_ex (threadid=139981952394816, thread_return=0x0, clockid=0, abstime=0x0, block=<optimized out>) at ./nptl/pthread_join_common.c:105
#4  0x00007f501eb66327 in std::thread::join() () from target:/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x000055eacae714dd in ?? ()
#6  0x000055eacae666b3 in ?? ()
#7  0x00007f501e784d90 in __libc_start_call_main (main=main@entry=0x55eacae660b0, argc=argc@entry=5, argv=argv@entry=0x7ffe11656278) at ../sysdeps/nptl/libc_start_call_main.h:58
#8  0x00007f501e784e40 in __libc_start_main_impl (main=0x55eacae660b0, argc=5, argv=0x7ffe11656278, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffe11656268) at ../csu/libc-start.c:392
#9  0x000055eacae6a265 in ?? ()
```

Things, that I'm already tried in my attempts to fix:
1) increase `nofile` limit for `apache2` in `envvars`
2) increase `memlock` limit for `apache2` service via `systemd`
2) increase `nofile` and `memlock` for `zoneminder` service via `systemd`

**Comment by connortechnology** [comment]
1.36.12 is ancient.  This issue has been solved a long time ago.  Update. You will need to go to https://zmrepo.zoneminder.com to use our packages as debian has not updated.
